### ISSUE TITLE
How to change the number of samples for clustering?

### ISSUE THREAD

**Issue by gullalc** [yenchanghsu/NNclustering#1]
There seems to be no way or an argument to change the number of samples that are used for making pairs for training the clustering algorithm.

**Comment by yenchanghsu** [comment]
Please check our new PyTorch-based implementation: [https://github.com/GT-RIPL/L2C](https://github.com/GT-RIPL/L2C)
In that new repository, you can custom the mask argument to select the desired pairs in the pair enumeration function.

**Comment by gullalc** [comment]
Thanks.
